# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 11:52
from __future__ import unicode_literals

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_auto_20180626_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, null=True),
        ),
    ]
