# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_auto_20180627_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='car_type',
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.Driver'),
        ),
    ]
